Repository wp-graphql/wpgraphql-ide, pull requests merged in 2024-03, with the labels that each got.

#61 feat: support plugin registration for the IDE
  package-lock.json
  package.json
  phpcs.xml.dist
  plugins/README.md
  plugins/help/HelpCard.js
  plugins/help/HelpPanel.js
  plugins/help/README.md
  plugins/help/help.php
  plugins/help/img/readme-img.png
  plugins/help/index.js
  src/App.jsx
  src/components/Editor.jsx
  src/components/EditorDrawer.jsx
  src/index.js
  src/store/index.js
  webpack.config.js
  wpgraphql-ide.php
Labels: enhancement, feature porting

#60 Allow registration of custom buttons
  .github/workflows/wordpress-coding-standards.yml
  ACTIONS_AND_FILTERS.md
  CONTRIBUTING.md
  README.md
  composer.json
  package-lock.json
  package.json
  plugins/help/HelpCard.js
  plugins/help/HelpPanel.js
  plugins/help/index.js
  src/App.jsx
  src/components/Editor.jsx
  src/components/EditorDrawer.jsx
  src/components/toolbarButtons/CopyQueryButton.jsx
  src/components/toolbarButtons/MergeFragmentsButton.jsx
  src/components/toolbarButtons/PrettifyButton.jsx
  src/components/toolbarButtons/ShareDocumentButton.jsx
  src/hooks/useCopyToClipboard.js
  src/index.js
  src/store/index.js
  tests/e2e/specs/drawer.spec.js
  tests/unit/specs/GraphiQLToolbar.test.js
  tests/unit/specs/Help.test.js
  webpack.config.js
  wpgraphql-ide.php
Labels: feature porting

#76 Consistent admin bar pattern
  phpcs.xml.dist
  src/components/EditorDrawer.jsx
  wpgraphql-ide.php
Labels: enhancement
